# Specify base image

FROM node:14-alpine

WORKDIR '/app'

# copy package.json
COPY package.json .

# Install some dependencies
RUN npm install

# Now Copy any changed files
COPY . .

# Default command
CMD ["npm", "run", "start"]